version: '3.1'

services:
  app:
    build: ./frontend
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: postgres:12.8-alpine
    restart: always
    volumes:
      - ./backend/app/account.sql:/docker-entrypoint-initdb.d/account.sql
      - ./backend/postgres_config_listen.conf:/docker-entrypoint-initdb.d/postgres_config_listen.conf
      - ./backend/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: royce
      POSTGRES_DB: card_game
      POSTGRES_PASSWORD: password

  game:
    build: ./backend
    ports:
      - "8080:8080"
